### ISSUE TITLE
“stage1-geometry” take a long time 

### ISSUE THREAD

**Issue by 1406428260** [xhuangcv/humannorm#1]
great job!
GPU tesla v100 32g
![image](https://github.com/xhuangcv/humannorm/assets/41857725/6a4c5a71-0af8-44bd-8007-ccfa0cad0a4a)

Is that normal?
how to speed up ?

**Comment by xhuangcv** [comment]
Hi, the code has been tested on a 3090 GPU with 24 GB of memory. The generation of geometry takes approximately 1.5 hours.

**Comment by 1406428260** [comment]
thanks
