### ISSUE TITLE
Dataset preparation for normal-adapted and depth-adapted diffusion models.

### ISSUE THREAD

**Issue by linziqu** [xhuangcv/humannorm#15]
Hi, I find in the supp you mention"For each model, we render a set of 120 images, each set comprising depth maps, normal maps, and color maps."

I am curious about you render 40 depth maps, 40 normal maps, and 40 color maps for each 3d human model? And then augment each image by dividing the human body into four distinct sections?

May I know the specific parameters for rendering the multiview images?

**Comment by xhuangcv** [comment]
Hi, for each model, we render a total of 120 images, divided as follows: 30 images for the head, 30 images for the upper body, 30 images for the lower body, and 30 images for the full body. These 30 images are evenly distributed in a ring with a radius of 1. You can adjust FOV and radius according to your needs.

**Comment by xhuangcv** [comment]
For each camera position, we render 3 images: RGB, normal and depth.

**Comment by xhuangcv** [comment]
For each camera position, we render 3 types of images: RGB, normal, and depth. This results in a total of 360 images.
