### ISSUE TITLE
Questions about Avatars

### ISSUE THREAD

**Issue by sunwonlikeyou** [xhuangcv/humannorm#3]
I wonder why avatars have so big limbs and faces.
It looks like SD Gundams.
Geometry model is not trained those data but I don't know why they look like.

**Comment by xhuangcv** [comment]
Hi, the issue stems from the part-based optimization. A potential solution would be to incorporate a global SDF loss that is based on the SMPLX mesh. This approach could effectively mitigate the excessive expansion of limbs.

**Comment by sunwonlikeyou** [comment]
Thanks!!
