### ISSUE TITLE
Fine-tuning text-to-normal Diffusion

### ISSUE THREAD

**Issue by KhanhNgoDuy** [xhuangcv/humannorm#6]
In Sec. 4.2.1, you " adapt a text-to-image diffusion model into a text-to-normal diffusion model".
Can you describe this process?

**Comment by xhuangcv** [comment]
Hi, we fine-tuned SD1.5 using text-normal pairs. The fine-tuning code is based on the text-to-image example in Diffusers. You can find more details in our supplementary material. After fine-tuning SD1.5, we can generate normal maps by providing text prompts.
