### ISSUE TITLE
Design choice on DMTet

### ISSUE THREAD

**Issue by KhanhNgoDuy** [xhuangcv/humannorm#7]
Hi, can you elaborate on the choice of DMTet for 3D generation model?
I mean it's a quite old paper, while there're more recent, advance method.

**Comment by xhuangcv** [comment]
Hi, you have the flexibility to employ alternative 3D representations. You can modify the 3D representation according to Threestudio's implementations, such as NeRF and 3D Gaussian Splatting. However, these representations may struggle to extract detailed geometry.
