### ISSUE TITLE
微调问题

### ISSUE THREAD

**Issue by zhou431496** [xhuangcv/humannorm#8]
能提供微调代码吗，如果我认为你是通过sb1.5获得图像然后利用最先进的法线估计算法估计法线，深度也是如此。获得配对的数据然后分贝微调sb1.5这样。那sb1.5和sb2.1甚至sb3.0对模型的性能应该有所影响吧

**Comment by xhuangcv** [comment]
Hi, our fine-tuning code is based on the text-to-image example in Diffusers. You can train your model using this code. Yes, the SD 2.1 may enhance our methods.

**Comment by zhou431496** [comment]
> Hi, our fine-tuning code is based on the text-to-image example in Diffusers. You can train your model using this code. Yes, the SD 2.1 may enhance our methods.

你能开源你的微调数据集嘛
